# Generated by Django 4.1.7 on 2023-02-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0038_remove_relationship_father_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dateissued',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='education',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employeeid',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employeetype',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='lastwork',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='othername',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='tinnumber',
        ),
    ]
