# Generated by Django 4.1.7 on 2023-02-23 11:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0039_remove_employee_bio_remove_employee_dateissued_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AlterField(
            model_name='employee',
            name='region',
            field=models.CharField(choices=[('Tamazret', 'Tamazret'), ('Ashanti', 'Taouejout'), ('Bono East', 'zaten'), ('Bono', 'laffam'), ('Central', 'Haddej'), ('Eastern', 'Techin'), ('North East', 'Douiuira'), ('Northen', 'zraoua'), ('Oti', 'Mzatta'), ('Savannah', 'Beni zalten')], default='Greater Accra', help_text='what region of the country(Ghana) are you from ?', max_length=20, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('Monsieur', 'Monsieur'), ('Madame', 'Madame')], default='Monsieur', max_length=9, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ssnitnumber',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numéro CIN'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+21650000000', help_text='Enter number with Country Code Eg. +233240000000', max_length=128, region=None, verbose_name='Phone Number (Example +233240000000)'),
        ),
    ]
